[[S2Geography]]
arch = "aarch64"
git-tree-sha1 = "42f0622c49b30cbd36b6f74458af5471425d6f29"
os = "macos"

    [[S2Geography.download]]
    sha256 = "830aeef19ba5c7097913b168caecd04e3257150269240bc20e2d4d8a25b17edc"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.aarch64-apple-darwin.tar.gz"
[[S2Geography]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1dff9cd28cf17807a056c271584796051765eca"
libc = "glibc"
os = "linux"

    [[S2Geography.download]]
    sha256 = "b78c90fc0ba854147e7afb6347ba360a45aae63550bdbfdbff2849e8520a0e52"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[S2Geography]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d1c758b729487f49e532a3da93bcf871348518f"
libc = "musl"
os = "linux"

    [[S2Geography.download]]
    sha256 = "ae782e4bde93138f4389ed6c1f76fc7a31b4f9db12b60b3995fb53c2debde25c"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[S2Geography]]
arch = "x86_64"
git-tree-sha1 = "347520af1048a11fffebb49633999b7aded4f2a2"
os = "macos"

    [[S2Geography.download]]
    sha256 = "fdf32693a18179f3bd225b84afc7eb1403648cbf67fb2cc3ff410bb1d6e8862c"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.x86_64-apple-darwin.tar.gz"
[[S2Geography]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18ff532df36f9517d04ea1da9f86929a3273d8dc"
libc = "glibc"
os = "linux"

    [[S2Geography.download]]
    sha256 = "5b883f5c4fd10d7f807410d7e1cfafe77ce1c751da23b689ee3410fe12829403"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[S2Geography]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f357b6bbc416039de91e95ae473ab4cc788973e8"
libc = "musl"
os = "linux"

    [[S2Geography.download]]
    sha256 = "c3f74fb7a820da4cf1e18bd8d82689b47df8be04ccd39751cfeb00424e5915a1"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[S2Geography]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58e38df885bbf94f65a7cddfe49e33a6f7c4cf87"
os = "windows"

    [[S2Geography.download]]
    sha256 = "4f67fdc93529b05b542aa6b474a43dd40c6011e0474c19c92ae53b9627e7b965"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.4.0+0/S2Geography.v0.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
