[[S2Geography]]
arch = "aarch64"
git-tree-sha1 = "b720c556fb8532a2c8ad971a226606e42a787086"
os = "macos"

    [[S2Geography.download]]
    sha256 = "34d81a9b3f62c28377645229e0cb2e457d4b6376dd147561bb0d3c5914be60f4"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.aarch64-apple-darwin.tar.gz"
[[S2Geography]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3c8785f594d52ab5830c1820660a089ea78892a"
libc = "glibc"
os = "linux"

    [[S2Geography.download]]
    sha256 = "4046f54bf30b158102bcfb551b57fafeae033ac2529db664db4a036cc3f46503"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[S2Geography]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a342c7d48f81513b752454a17f97b9112f5283a8"
libc = "musl"
os = "linux"

    [[S2Geography.download]]
    sha256 = "02312c6af7a30ec2f37ee8dbdf770875c63a76d60505141d5150f3ea8bf5ea5a"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[S2Geography]]
arch = "x86_64"
git-tree-sha1 = "90845d6ada60083bfd60a55f08531b069525b783"
os = "macos"

    [[S2Geography.download]]
    sha256 = "b166ac3d57afd6ed195f4392d45002c7457e76f49039cdcdc0e98665bbbd3378"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.x86_64-apple-darwin.tar.gz"
[[S2Geography]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97dacc7593e13c057b67a3b139833d29f7f3edfc"
libc = "glibc"
os = "linux"

    [[S2Geography.download]]
    sha256 = "f4c09fa7f3273392b782d8b6443986a14f05947947ff366bec3d9ed13ca0a72c"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[S2Geography]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0aeb040f854095b78f3da9bf7e6ccf3fd30e637"
libc = "musl"
os = "linux"

    [[S2Geography.download]]
    sha256 = "0fed7de9563416c7b57c2ec6bf4c5f3e3f999cef083f88ea5ded686e307019fc"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[S2Geography]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4534d2749c05b7a191bc0e6a57fbd71d0fc1c864"
os = "windows"

    [[S2Geography.download]]
    sha256 = "323317fd03b8a9568ec0bb994e9f53efe4caf46ea6c9e37d2c92a19174387c37"
    url = "https://github.com/JuliaBinaryWrappers/S2Geography_jll.jl/releases/download/S2Geography-v0.3.0+0/S2Geography.v0.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
