# Autogenerated wrapper script for S2Geography_jll for x86_64-apple-darwin
export libs2geography

using abseil_cpp_jll
using S2Geometry_jll
using nanoarrow_jll
JLLWrappers.@generate_wrapper_header("S2Geography")
JLLWrappers.@declare_library_product(libs2geography, "@rpath/libs2geography.dylib")
function __init__()
    JLLWrappers.@generate_init_header(abseil_cpp_jll, S2Geometry_jll, nanoarrow_jll)
    JLLWrappers.@init_library_product(
        libs2geography,
        "lib/libs2geography.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
