# Autogenerated wrapper script for S2Geography_jll for x86_64-w64-mingw32-cxx11
export libs2geography, libs2geography_c

using abseil_cpp_jll
using OpenSSL_jll
using S2Geometry_jll
using nanoarrow_jll
JLLWrappers.@generate_wrapper_header("S2Geography")
JLLWrappers.@declare_library_product(libs2geography, "libs2geography.dll")
JLLWrappers.@declare_library_product(libs2geography_c, "libs2geography_c.dll")
function __init__()
    JLLWrappers.@generate_init_header(abseil_cpp_jll, OpenSSL_jll, S2Geometry_jll, nanoarrow_jll)
    JLLWrappers.@init_library_product(
        libs2geography,
        "bin\\libs2geography.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libs2geography_c,
        "bin\\libs2geography_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
